services:
  - type: web
    name: libretranslate-belux
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "8394f366f9e24d6f8657ec78581fb5ca"
      - key: PORT
        value: "10000" 
